#include "POGameplayTags.h"

// PROTOTYPE
UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_CONTEXT_STAGE_LOADED, "Prototype.Context.StageLoaded");
UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_CONTEXT_STAGE_PENDING, "Prototype.Context.StagePending");
UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_CONTEXT_STAGE_READY, "Prototype.Context.StageReady");
UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_CONTEXT_STAGE_SLOTS_FULFILLED, "Prototype.Context.StageSlotsFulfilled");

UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_CONTEXT_COMBAT_REQUIRED_COMBATANTS, "Prototype.Context.Combat.RequiredCombatants");

UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_FIELD, "Prototype.Field");
UE_DEFINE_GAMEPLAY_TAG(TAG_PROTOTYPE_FIELD_BATTLE, "Prototype.Field.Battle");

// ALPHA
UE_DEFINE_GAMEPLAY_TAG(TAG_ALPHA_FIELD, "Field");